import "./about.css"

export function About() {
    return (
        <section id="about">
            <h1>About</h1>
            <p>This is a CSS only project. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ullam possimus, exercitationem veniam quisquam tenetur a aperiam. Expedita est eveniet adipisci magni quaerat! Nostrum officiis quaerat sed suscipit error esse quidem. Made to get better at designing stuff with CSS.</p>
            <p>That's it :). Pellentesque bibendum congue justo non posuere. Etiam efficitur erat vitae eleifend euismod. Aliquam quam purus, laoreet sit amet mi in, tempor cursus velit. Pellentesque eros purus, posuere sed fringilla ultricies, sollicitudin sed erat. Maecenas sagittis orci a elit commodo, et tempor felis maximus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean vel vulputate enim.</p>
            <p>Placeholder Placeholder. Yada Yada Yada. Nothing to see here. Mauris molestie pellentesque dolor at egestas. Sed vel odio at ante molestie hendrerit quis id est. Ut leo est, semper ac erat id, maximus blandit massa. Suspendisse ac dui pellentesque, aliquet velit et, euismod eros. Etiam pellentesque, ex id mollis sodales, mauris metus volutpat turpis, a sollicitudin dolor lectus eget sem. Nullam pretium ac orci at lobortis. Mauris viverra tincidunt erat quis ornare. Quisque viverra justo nec ex auctor gravida. Nullam ac fringilla tortor. Cras euismod enim fringilla erat porttitor, et condimentum sem cursus.</p>
            <p>Mauris aliquet sit amet urna vel rhoncus. Nulla sed magna pretium, elementum dolor et, sagittis est. Maecenas in diam lacus. Integer in ex eu turpis molestie pharetra vel a mauris. Duis luctus lorem eget venenatis ultricies. Integer dignissim ex in leo malesuada, nec feugiat metus venenatis. Maecenas cursus vel urna ac ultrices. Nulla facilisi. Praesent id pretium sapien. Nulla faucibus lacus id malesuada dignissim. Vivamus dapibus justo tellus, eleifend efficitur odio varius nec. Donec suscipit finibus hendrerit. Nullam vitae tristique sapien. Ut nec mi consectetur lectus hendrerit porttitor. Sed consectetur lacus id est vulputate, a porttitor diam hendrerit. Sed nibh tellus, tempor elementum consequat eget, laoreet ac nisl.</p>
            <p>In hac habitasse platea dictumst. In in augue faucibus, luctus nulla a, imperdiet metus. Still nothing. Proin molestie a augue sit amet mattis. Nulla fringilla, ipsum ac mollis condimentum, odio metus placerat nisi, eget efficitur libero metus vitae lorem. Donec ultrices justo tellus, at congue turpis sagittis et. Ut at scelerisque orci. Vestibulum quis odio pulvinar, placerat nisl eget, vulputate justo. Nulla porta ornare nunc in ullamcorper. Integer quis velit eu lorem euismod laoreet sed sed ex. Nullam convallis maximus elementum. Phasellus ornare commodo est, ac vulputate lectus maximus rutrum. Donec vitae leo id ante luctus tempor id non quam. Duis id aliquam elit.</p>
        </section>
    )
};